import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

Color whiteColor = Color(0xffFFFFFF);
Color backgroundOnBoardingCOlor = Color(0xffC9FBEF);
Color blackColor = Color(0xff333333);
Color black2Color = Color(0xff444444);
Color greyColor = Color(0xff8E8D8D);
Color cyanColor = Color(0xff00A9B6);
Color cyan2Color = Color(0xff94F7E5);
Color cyan3Color = Color(0xffC9FBEF);
Color cyan4Color = Color(0xffCCFAEF);
Color greyColor2 = Color(0xffF3F3F3);
Color greyColor3 = Color(0xffC4C4C4);
Color greyColor4 = Color(0xffDADADA);
Color greyColor5 = Color(0xffF4F4F4);
Color greyColor6 = Color(0xffA6A7A8);
Color greyColor7 = Color(0xff828282);
Color greyColor8 = Color(0xff646464);
Color facebookColor = Color(0xff0E70E3);
Color appleColor = Color(0xff1C1C1C);
Color greenColor = Color(0xff5BA41E);
Color yayasanColor = Color(0xff8E9092);
Color blueColor = Color(0xff0E70E3);
Color redColor = Color(0xffFF5031);
Color red2Color = Color(0xffFF5031);


TextStyle blackSBTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w600, color: blackColor);
TextStyle blackRTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w400, color: blackColor);
TextStyle blackSB2TextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w500, color: black2Color);
TextStyle blackMTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w600, color: black2Color);
TextStyle greyRTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w400, color: greyColor);
TextStyle greyR2TextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w400, color: greyColor6);
TextStyle greyR3TextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w400, color: greyColor7);
TextStyle greyR4TextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w400, color: greyColor8);
TextStyle greySBTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w600, color: greyColor3);
TextStyle greyMTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w500, color: greyColor7);
TextStyle greyM2TextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w500, color: greyColor4);
TextStyle whiteSBTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w600, color: whiteColor);
TextStyle whiteRTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w400, color: whiteColor);
TextStyle whiteMTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w500, color: whiteColor);
TextStyle cyanRTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w400, color: cyanColor);
TextStyle cyanSBTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w600, color: cyanColor);
TextStyle cyanMTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w500, color: cyanColor);
TextStyle cyanM2TextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w500, color: cyan2Color);
TextStyle yayasanTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w500, color: yayasanColor);
TextStyle redMTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w500, color: redColor);
TextStyle greenMTextStyle = GoogleFonts.poppins(fontWeight: FontWeight.w500, color: greenColor);